const SUPABASE_URL='https://kjmotqzbifxsnscvtysz.supabase.co';
const SUPABASE_KEY='sb_publishable_2LKsNXHeEemj9wnxr71eyw_ASH4ZFLK';
const db=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{storageKey:'pmb_yunaji_admin_session',persistSession:true,autoRefreshToken:true,detectSessionInUrl:false}});
const $=id=>document.getElementById(id);const rpc=async(name,args={})=>{const r=await db.rpc(name,args);if(r.error)throw r.error;return r.data};const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));const money=n=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(Number(n)||0);const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Jakarta',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
function show(id){document.querySelectorAll('.view').forEach(x=>x.classList.add('hidden'));$(id).classList.remove('hidden');document.querySelectorAll('.tabs button').forEach(b=>b.classList.toggle('active',b.dataset.view===id));if(id==='dashboard')dashboard();if(id==='cash')cash();if(id==='staff')staff()}
async function login(e){e.preventDefault();$('adminMsg').textContent='Masuk...';try{const r=await db.auth.signInWithPassword({email:$('email').value,password:$('password').value});if(r.error)throw r.error;const role=await rpc('kasir_current_role');if(!['admin','owner'].includes(String(role||'').toLowerCase())){await db.auth.signOut();throw new Error('Akun ini bukan Admin/Pemilik.')}enter()}catch(e){$('adminMsg').textContent=e.message}}
function enter(){$('adminLogin').classList.add('hidden');$('adminApp').classList.remove('hidden');dashboard();cash();staff()}
async function dashboard(){try{const d=(await rpc('kasir_admin_dashboard_ui',{p_mulai:$('from')?.value||today(),p_selesai:$('to')?.value||today()}))?.[0];if(!d)return;$('dashDate').textContent=today();$('dashboardStats').innerHTML=`<div class="stat"><span>Total Pasien</span><strong>${d.total_pasien}</strong></div><div class="stat"><span>Total Pelayanan</span><strong>${d.total_pelayanan}</strong></div><div class="stat"><span>Total Pemasukan</span><strong>${money(d.total_pemasukan)}</strong></div><div class="stat"><span>Total Pengeluaran</span><strong>${money(d.total_pengeluaran)}</strong></div>`}catch(e){$('adminMsg').textContent=e.message}}
async function tx(){try{const r=await rpc('kasir_admin_transaksi_final',{p_mulai:$('from').value,p_selesai:$('to').value,p_subjenis:$('kind').value||null});$('txRows').innerHTML=(r||[]).map(x=>`<tr><td>${esc(x.tanggal)}</td><td>${esc(x.nomor)}</td><td>${esc(x.subjenis)}</td><td>${esc(x.pasien||x.produk||'')}</td><td>${esc(x.kategori)}</td><td>${esc(x.pelaksana||'')}</td><td>${esc(x.operator||'')}</td><td>${esc(x.metode||'')}</td><td>${money(x.nominal)}</td></tr>`).join('')||'<tr><td colspan="9">Tidak ada data.</td></tr>'}catch(e){$('txRows').innerHTML=`<tr><td colspan="9">${esc(e.message)}</td></tr>`}}
async function cash(){try{const k=(await rpc('kasir_admin_kas_hari_ini'))?.[0];if(!k){$('cashStats').innerHTML='<div class="stat"><span>Status</span><strong>BELUM ADA KAS</strong></div>';return}$('cashStats').innerHTML=`<div class="stat"><span>Kas Awal</span><strong>${money(k.kas_awal)}</strong></div><div class="stat"><span>Kas Masuk</span><strong>${money(k.kas_masuk)}</strong></div><div class="stat"><span>Kas Keluar</span><strong>${money(k.kas_keluar)}</strong></div>`}catch(e){$('cashMsg').textContent=e.message}}
async function openCash(){try{await rpc('admin_open_cash',{p_date:today(),p_opening_cash:Number($('opening').value),p_notes:'Dibuka Admin'});$('cashMsg').textContent='Kas berhasil dibuka.';cash()}catch(e){$('cashMsg').textContent=e.message}}
async function closeCash(){try{const k=(await rpc('kasir_admin_kas_hari_ini'))?.[0];if(!k?.kas_id)throw new Error('Kas hari ini belum dibuka.');const r=await rpc('admin_close_cash',{p_session_id:k.kas_id,p_physical_cash:Number($('physical').value),p_notes:$('closeNote').value});const x=Array.isArray(r)?r[0]:r;$('cashMsg').textContent=`Kas ditutup. Selisih: ${money(x?.difference)}`;cash()}catch(e){$('cashMsg').textContent=e.message}}
async function logbook(){try{const r=await rpc('kasir_admin_logbook_final',{p_mulai:$('logFrom').value,p_selesai:$('logTo').value,p_cari:$('search').value||null});$('logRows').innerHTML=(r||[]).map(x=>`<tr><td>${esc(x.tanggal_waktu)}</td><td>${esc(x.nama_pasien)}</td><td>${x.umur}</td><td>${esc(x.pelayanan)}</td><td>${esc(x.pelaksana)}</td><td>${esc(x.operator)}</td></tr>`).join('')||'<tr><td colspan="6">Tidak ada data.</td></tr>'}catch(e){$('logRows').innerHTML=`<tr><td colspan="6">${esc(e.message)}</td></tr>`}}
async function staff(){try{const r=await rpc('kasir_admin_get_staff');$('staffRows').innerHTML=(r||[]).map(x=>`<tr><td>${esc(x.nama)}</td><td>${esc(x.jabatan)}</td><td>${x.aktif?'Aktif':'Nonaktif'}</td></tr>`).join('')}catch(e){}}
async function boot(){const d=today();$('from').value=d;$('to').value=d;$('logFrom').value=d;$('logTo').value=d;$('loginForm').onsubmit=login;$('logout').onclick=async()=>{await db.auth.signOut();location.reload()};document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>show(b.dataset.view));$('loadTx').onclick=tx;$('loadLog').onclick=logbook;$('adminOpen').onclick=openCash;$('adminClose').onclick=closeCash;try{const s=(await db.auth.getSession()).data.session;if(s){const role=await rpc('kasir_current_role');if(['admin','owner'].includes(String(role||'').toLowerCase()))enter()}}catch{}}boot();