(function(){
  const URL='https://kjmotqzbifxsnscvtysz.supabase.co';
  const KEY='sb_publishable_2LKsNXHeEemj9wnxr71eyw_ASH4ZFLK';
  if(document.body.dataset.page!=='admin') return;
  const db=window.supabase.createClient(URL,KEY,{auth:{storageKey:'pmb_yunaji_admin_session',persistSession:true,autoRefreshToken:true,detectSessionInUrl:false}});
  const q=id=>document.getElementById(id);
  window.adminDb=db;
  window.rpc=async(name,args={})=>{const r=await db.rpc(name,args);if(r.error)throw r.error;return r.data};
  window.$=window.$||q;
  window.fmt=window.fmt||((n)=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(Number(n)||0));
  window.today=window.today||(()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Jakarta',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date()));
  window.esc=window.esc||((v)=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c])));
  window.msg=window.msg||((id,t)=>{if(q(id))q(id).textContent=t||''});
  window.showAdmin=(id)=>{document.querySelectorAll('.admin-panel').forEach(x=>x.classList.add('hidden'));q(id)?.classList.remove('hidden');document.querySelectorAll('.admin-nav-btn').forEach(x=>x.classList.toggle('active',x.dataset.panel===id));};
  async function isAdmin(){const role=await db.rpc('kasir_current_role');return ['admin','owner'].includes(String(role.data||'').toLowerCase())}
  async function hydrateSettings(){try{const s=Object.fromEntries((await window.rpc('kasir_get_pengaturan')||[]).map(x=>[x.kode,x.nilai||'']));const map={setBrandName:s.brand_name||s.NAMA_PMB||'',setLoginTitle:s.login_title||'Kasir Klinik',setTagline:s.tagline||'',setLoginSubtitle:s.login_subtitle||'Pilih nama PJ untuk masuk. Tidak perlu password.',setLogoUrl:s.logo_url||'',setPrimaryColor:s.primary_color||'#6f25d9',setSecondaryColor:s.secondary_color||'#a12cf0',setAccentColor:s.accent_color||'#ec2d9a',setBackgroundColor:s.background_color||'#f5f2fb'};Object.entries(map).forEach(([id,v])=>{if(q(id))q(id).value=v});const staff=await window.rpc('kasir_admin_get_staff');if(q('staffRows'))q('staffRows').innerHTML=(staff||[]).map(x=>`<tr><td>${esc(x.nama)}</td><td>${esc(x.jabatan)}</td><td>${x.aktif?'Aktif':'Nonaktif'}</td><td>${x.urutan}</td><td><button class="secondary staff-edit" data-id="${x.id}">Edit</button></td></tr>`).join('')||'<tr><td colspan="5">Belum ada PJ.</td></tr>';}catch(e){console.warn('settings hydrate',e)}}
  window.enterAdmin=async()=>{q('loginView')?.classList.add('hidden');q('appView')?.classList.remove('hidden');showAdmin('dashboardPanel');try{await hydrateSettings();await adminRefreshCash();await window.adminDash();if(typeof window.initRekapPelaksana==='function')await window.initRekapPelaksana();document.dispatchEvent(new CustomEvent('pmb-admin-ready'));}catch(e){msg('dashboardMessage',e.message)}};
  window.adminLogin=async(e)=>{e.preventDefault();msg('loginMessage','Memeriksa akun admin...');try{const r=await db.auth.signInWithPassword({email:q('adminEmail').value.trim(),password:q('adminPassword').value});if(r.error)throw r.error;if(!(await isAdmin())){await db.auth.signOut({scope:'local'});throw new Error('Akun ini bukan Admin/Owner.')}await enterAdmin();}catch(err){msg('loginMessage','Login admin gagal: '+(err.message||err))}};
  window.adminDash=async()=>{try{const from=q('reportFrom')?.value||today(),to=q('reportTo')?.value||today();const d=(await window.rpc('kasir_admin_dashboard_ui',{p_mulai:from,p_selesai:to}))?.[0];q('dashboardStats').innerHTML=d?`<div class="stat"><span>Total Pasien</span><strong>${d.total_pasien}</strong></div><div class="stat"><span>Total Pelayanan</span><strong>${d.total_pelayanan}</strong></div><div class="stat"><span>Pelayanan Selesai</span><strong>${d.pelayanan_selesai}</strong></div><div class="stat"><span>Total Pemasukan</span><strong>${fmt(d.total_pemasukan)}</strong></div><div class="stat"><span>Total Pengeluaran</span><strong>${fmt(d.total_pengeluaran)}</strong></div><div class="stat"><span>Saldo Kas</span><strong>${fmt(d.saldo_kas)}</strong></div>`:'<p class="muted">Belum ada data.</p>';}catch(e){msg('dashboardMessage',e.message)}};
  window.adminTx=async()=>{try{const rows=await window.rpc('kasir_admin_transaksi_final',{p_mulai:q('txFrom').value,p_selesai:q('txTo').value,p_subjenis:q('txType').value||null});q('txRows').innerHTML=(rows||[]).map(x=>`<tr><td>${new Date(x.tanggal).toLocaleString('id-ID')}</td><td>${esc(x.nomor)}</td><td>${esc(x.subjenis)}</td><td>${esc(x.pasien||x.produk||'-')}</td><td>${esc(x.kategori||'-')}</td><td>${esc(x.pelaksana||'-')}</td><td>${esc(x.operator||'-')}</td><td>${esc(x.metode||'-')}</td><td>${fmt(x.nominal)}</td></tr>`).join('')||'<tr><td colspan="9">Belum ada transaksi.</td></tr>';msg('txMessage',`${rows?.length||0} transaksi`)}catch(e){msg('txMessage',e.message)}};
  window.adminLog=async()=>{try{const rows=await window.rpc('kasir_admin_logbook_final',{p_mulai:q('logFrom').value,p_selesai:q('logTo').value,p_cari:q('logSearch').value.trim()||null});q('logRows').innerHTML=(rows||[]).map(x=>{const d=new Date(x.tanggal_waktu);return `<tr><td>${d.toLocaleDateString('id-ID')}</td><td>${d.toLocaleTimeString('id-ID',{hour:'2-digit',minute:'2-digit'})}</td><td>${esc(x.nama_pasien)}</td><td>${x.umur}</td><td>${esc(x.pelayanan)}</td><td>${esc(x.pelaksana)}</td><td>${esc(x.operator)}</td></tr>`}).join('')||'<tr><td colspan="7">Belum ada logbook.</td></tr>';msg('logMessage',`${rows?.length||0} pasien`)}catch(e){msg('logMessage',e.message)}};
  window.adminOpen=async()=>{const n=Number(q('adminOpeningCash').value);if(!Number.isInteger(n)||n<0){msg('adminCashMessage','Kas awal tidak valid.');return}if(!confirm(`Buka kas hari ini dengan ${fmt(n)}?`))return;try{await window.rpc('kasir_buka_kas_harian',{p_kas_awal:n,p_catatan:'Dibuka Admin'});q('adminOpeningCash').value='';msg('adminCashMessage','Kas berhasil dibuka.');await adminRefreshCash();}catch(e){msg('adminCashMessage',e.message)}};
  window.adminClose=async()=>{const n=Number(q('adminClosingCash').value);if(!Number.isFinite(n)||n<0){msg('adminCashMessage','Kas fisik tidak valid.');return}if(!confirm(`Tutup kas hari ini dengan kas fisik ${fmt(n)}?`))return;try{await window.rpc('kasir_tutup_kas_harian',{p_kas_fisik:n,p_catatan:q('adminClosingNote').value.trim()||null});q('adminClosingCash').value='';q('adminClosingNote').value='';msg('adminCashMessage','Kas berhasil ditutup.');await adminRefreshCash();}catch(e){msg('adminCashMessage',e.message)}};
  async function adminRefreshCash(){try{const d=(await window.rpc('kasir_admin_kas_hari_ini'))?.[0];if(!d){q('adminCashStatus').textContent='Belum dibuka';q('adminCashDetail').textContent='Kas hari ini belum dibuka.';q('cashStats').innerHTML='';return}q('adminCashStatus').textContent=d.status;q('adminCashDetail').textContent=`Kas awal ${fmt(d.kas_awal)} · Masuk ${fmt(d.kas_masuk)} · Keluar ${fmt(d.kas_keluar)} · Sistem ${fmt(d.kas_sistem)}${d.status==='CLOSED'?` · Fisik ${fmt(d.kas_fisik)} · Selisih ${fmt(d.selisih)}`:''}`;q('cashStats').innerHTML=`<div class="stat"><span>Kas Awal</span><strong>${fmt(d.kas_awal)}</strong></div><div class="stat"><span>Kas Masuk</span><strong>${fmt(d.kas_masuk)}</strong></div><div class="stat"><span>Kas Keluar</span><strong>${fmt(d.kas_keluar)}</strong></div><div class="stat"><span>Kas Sistem</span><strong>${fmt(d.kas_sistem)}</strong></div>`;}catch(e){msg('adminCashMessage',e.message)}}
  window.adminRefreshCash=adminRefreshCash;
  document.addEventListener('DOMContentLoaded',()=>{[50,250,600].forEach(ms=>setTimeout(async()=>{if(typeof window.initAdmin==='function'&&!window.__pmbAdminBooted){window.__pmbAdminBooted=true;try{await window.initAdmin()}catch(e){msg('loginMessage','Admin gagal dimuat: '+e.message)}}},ms));setTimeout(()=>adminRefreshCash(),700);});
})();
