const SUPABASE_URL='https://kjmotqzbifxsnscvtysz.supabase.co';
const SUPABASE_KEY='sb_publishable_2LKsNXHeEemj9wnxr71eyw_ASH4ZFLK';
const db=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{storageKey:'pmb_yunaji_clean_session',persistSession:true,autoRefreshToken:true,detectSessionInUrl:false}});
const $=id=>document.getElementById(id);
const rpc=async(name,args={})=>{const r=await db.rpc(name,args);if(r.error)throw r.error;return r.data};
let operator=null;
function msg(id,text=''){if($(id))$(id).textContent=text}
function escapeHtml(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function show(view){document.querySelectorAll('.view').forEach(x=>x.classList.add('hidden'));$(view)?.classList.remove('hidden');document.querySelectorAll('.tabs button').forEach(b=>b.classList.toggle('active',b.dataset.view===view));if(view==='patients')loadPatients();if(view==='mine')loadMine()}
async function loadStaff(){try{const rows=await rpc('kasir_get_penanggung_jawab');$('staffList').innerHTML=(rows||[]).map(s=>`<button class="choice-btn" data-id="${s.id}"><span class="staff-avatar">PJ</span><span class="staff-text"><strong>${escapeHtml(s.nama||'')}</strong><span class="staff-role">${escapeHtml(s.jabatan||'PJ / Staff')}</span></span></button>`).join('')||'<p>Belum ada PJ aktif.</p>';document.querySelectorAll('.choice-btn').forEach(b=>b.onclick=()=>loginAs(Number(b.dataset.id)))}catch(e){msg('loginMsg','Gagal memuat daftar PJ: '+e.message)}}
async function loginAs(staffId){try{msg('loginMsg','Menyiapkan sesi kasir...');const old=(await db.auth.getSession()).data.session;if(old)await db.auth.signOut();const auth=await db.auth.signInAnonymously();if(auth.error)throw auth.error;await rpc('kasir_set_operator',{p_staff_id:staffId});await enterCashier()}catch(e){msg('loginMsg','Tidak bisa masuk: '+(e.message||e))}}
async function enterCashier(){const op=await rpc('kasir_current_operator');operator=Array.isArray(op)?op[0]:op;if(!operator)throw new Error('Operator belum terbentuk.');$('login').classList.add('hidden');$('cashier').classList.remove('hidden');$('operatorName').textContent=operator.nama||'Kasir';$('welcome').textContent=operator.nama||'Kasir';await loadMaster();await refreshCash();await loadMine()}
async function switchOperator(){await db.auth.signOut();operator=null;$('cashier').classList.add('hidden');$('login').classList.remove('hidden');await loadStaff()}
async function loadMaster(){const [services,performers,payments,products,categories]=await Promise.all([rpc('kasir_get_layanan'),rpc('kasir_get_penanggung_jawab'),rpc('kasir_get_metode_pembayaran'),rpc('kasir_get_produk'),rpc('kasir_get_kategori',{p_jenis:'PENGELUARAN'})]);fill('serviceType',services,'id','nama','Pilih pelayanan');fill('performer',performers,'id','nama','Pilih pelaksana');fill('servicePayment',payments,'id','nama','Pilih metode');fill('salePayment',payments,'id','nama','Pilih metode');fill('expensePayment',payments,'id','nama','Pilih metode');fill('product',products,'id','name','Pilih produk');fill('expenseCategory',categories,'id','nama','Pilih kategori');if(operator?.staff_id)$('performer').value=String(operator.staff_id)}
function fill(id,rows,key,label,placeholder){const el=$(id);if(!el)return;el.innerHTML=`<option value="">${placeholder}</option>`+(rows||[]).map(x=>`<option value="${x[key]}">${escapeHtml(x[label]??'')}</option>`).join('')}
async function refreshCash(){try{const rows=await rpc('kasir_status_kas_kasir');const k=Array.isArray(rows)?rows[0]:rows;const open=k?.status==='OPEN';$('cashStatus').textContent=open?'Kas hari ini: TERBUKA':'Kas hari ini: BELUM DIBUKA';$('cashState').textContent=open?'TERBUKA':'BELUM DIBUKA';$('cashStatus').className='status '+(open?'success':'');$('cashOpenArea').classList.toggle('hidden',open);$('cashAlready').classList.toggle('hidden',!open);document.querySelectorAll('#serviceForm button,#saleForm button,#expenseForm button').forEach(b=>b.disabled=!open);return open}catch(e){$('cashStatus').textContent='Status kas gagal dimuat';msg('cashMsg',e.message);return false}}
async function openCash(){try{msg('cashMsg','Membuka kas hari ini...');await rpc('kasir_buka_kas_harian',{p_kas_awal:0,p_catatan:'Dibuka oleh PJ/Staff'});msg('cashMsg','Kas hari ini berhasil dibuka.');await refreshCash()}catch(e){msg('cashMsg',e.message||String(e))}}
async function submitService(e){e.preventDefault();if(!(await refreshCash()))return msg('serviceMsg','Buka kas terlebih dahulu.');try{await rpc('kasir_input_pelayanan',{p_nama_pasien:$('patientName').value.trim(),p_umur:Number($('patientAge').value),p_kategori_id:Number($('serviceType').value),p_pelaksana_id:Number($('performer').value),p_metode_pembayaran_id:Number($('servicePayment').value),p_nominal:Number($('serviceAmount').value),p_catatan:$('serviceNote').value.trim()});e.target.reset();if(operator?.staff_id)$('performer').value=String(operator.staff_id);msg('serviceMsg','Pelayanan tersimpan dan otomatis masuk logbook.');await refreshHomeData()}catch(x){msg('serviceMsg',x.message||String(x))}}
async function submitSale(e){e.preventDefault();if(!(await refreshCash()))return msg('saleMsg','Buka kas terlebih dahulu.');try{await rpc('kasir_input_penjualan',{p_produk_id:$('product').value,p_jumlah:Number($('quantity').value),p_metode_pembayaran_id:Number($('salePayment').value),p_nominal:Number($('saleAmount').value),p_catatan:$('saleNote').value.trim()});e.target.reset();msg('saleMsg','Penjualan tersimpan.');}catch(x){msg('saleMsg',x.message||String(x))}}
async function submitExpense(e){e.preventDefault();if(!(await refreshCash()))return msg('expenseMsg','Buka kas terlebih dahulu.');try{await rpc('kasir_input_pengeluaran',{p_kategori_id:Number($('expenseCategory').value),p_metode_pembayaran_id:Number($('expensePayment').value),p_nominal:Number($('expenseAmount').value),p_catatan:$('expenseNote').value.trim()});e.target.reset();msg('expenseMsg','Pengeluaran tersimpan.');}catch(x){msg('expenseMsg',x.message||String(x))}}
async function loadPatients(){try{const rows=await rpc('kasir_riwayat_pasien_hari_ini');$('patientRows').innerHTML=(rows||[]).map(x=>`<tr><td>${escapeHtml(x.tanggal_waktu?new Date(x.tanggal_waktu).toLocaleTimeString('id-ID',{hour:'2-digit',minute:'2-digit'}):x.waktu||'-')}</td><td>${escapeHtml(x.nama_pasien||x.pasien||'')}</td><td>${x.umur??''}</td><td>${escapeHtml(x.pelayanan||x.jenis_pelayanan||'')}</td><td>${escapeHtml(x.pelaksana||'')}</td></tr>`).join('')||'<tr><td colspan="5">Belum ada pasien hari ini.</td></tr>'}catch(e){$('patientRows').innerHTML=`<tr><td colspan="5">${escapeHtml(e.message)}</td></tr>`}}
async function loadMine(){try{const rows=await rpc('kasir_rekap_saya');const r=Array.isArray(rows)?rows[0]:rows;$('minePatients').textContent=r?.jumlah_pasien??r?.total_pasien??0;$('mineServices').textContent=r?.jumlah_pelayanan??r?.total_pelayanan??0;$('patientCount').textContent=r?.jumlah_pasien??r?.total_pasien??0;$('serviceCount').textContent=r?.jumlah_pelayanan??r?.total_pelayanan??0}catch(e){}}
async function refreshHomeData(){await loadMine();if(!$('patients').classList.contains('hidden'))await loadPatients()}
async function boot(){document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>show(b.dataset.view));$('switchBtn').onclick=switchOperator;$('exitBtn').onclick=switchOperator;$('openCashBtn').onclick=openCash;$('serviceForm').onsubmit=submitService;$('saleForm').onsubmit=submitSale;$('expenseForm').onsubmit=submitExpense;await loadStaff();try{const s=(await db.auth.getSession()).data.session;if(s){const op=await rpc('kasir_current_operator');if(op?.length)await enterCashier();else await db.auth.signOut()}}catch(e){await db.auth.signOut().catch(()=>{})}}
boot();