const SUPABASE_URL='https://kjmotqzbifxsnscvtysz.supabase.co';
const SUPABASE_KEY='sb_publishable_2LKsNXHeEemj9wnxr71eyw_ASH4ZFLK';
const page=document.body.dataset.page,isKasir=page==='kasir';
const db=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{storageKey:isKasir?'pmb_yunaji_kasir_session':'pmb_yunaji_admin_session',persistSession:true,autoRefreshToken:true,detectSessionInUrl:false}});
const $=id=>document.getElementById(id),fmt=n=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(Number(n)||0),today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Jakarta',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
async function rpc(name,args={}){const r=await db.rpc(name,args);if(r.error)throw r.error;return r.data}
function msg(id,t){if($(id))$(id).textContent=t||''}
async function initKasir(){
 const staff=[['4','Bidan Yuna'],['3','Bidan Luvita'],['1','Bidan Yulli'],['2','Bidan Echa']];
 $('staffChoices').innerHTML=staff.map(x=>`<button class="choice-btn" data-id="${x[0]}">${x[1]}</button>`).join('');
 document.querySelectorAll('.choice-btn').forEach(b=>b.onclick=()=>loginKasir(+b.dataset.id));
 $('logoutBtn').onclick=()=>db.auth.signOut({scope:'local'});document.querySelectorAll('.menu-card').forEach(b=>b.onclick=()=>showPanel(b.dataset.panel));
 $('openCashBtn').onclick=openCash;$('closeCashBtn').onclick=closeCash;$('pelayananForm').onsubmit=savePelayanan;$('penjualanForm').onsubmit=savePenjualan;$('pengeluaranForm').onsubmit=savePengeluaran;$('produk').onchange=calcSale;$('produkJumlah').oninput=calcSale;
 const s=(await db.auth.getSession()).data.session;if(s){if(s.user?.is_anonymous)enterKasir();else db.auth.signOut({scope:'local'})}}
async function loginKasir(id){msg('loginMessage','Membuka sesi kasir...');const old=(await db.auth.getSession()).data.session;if(old)await db.auth.signOut({scope:'local'});const r=await db.auth.signInAnonymously();if(r.error){msg('loginMessage','Login gagal: '+r.error.message+' — aktifkan Anonymous Sign-Ins di Supabase.');return}try{await rpc('kasir_set_operator',{p_staff_id:id});enterKasir()}catch(e){msg('loginMessage',e.message);await db.auth.signOut({scope:'local'})}}
async function enterKasir(){const o=(await rpc('kasir_current_operator'))?.[0];if(!o){msg('loginMessage','Operator belum dipilih.');return}$('welcomeName').textContent=o.staff_name;$('operatorLabel').textContent=o.staff_name;$('loginView').classList.add('hidden');$('appView').classList.remove('hidden');await masters();await cashStatus();await rekap();await patients()}
async function masters(){const [ci,co,st,pay,prod]=await Promise.all([rpc('kasir_get_kategori',{p_jenis:'PEMASUKAN'}),rpc('kasir_get_kategori',{p_jenis:'PENGELUARAN'}),rpc('kasir_get_penanggung_jawab'),rpc('kasir_get_metode_pembayaran'),rpc('kasir_get_produk')]);$('pelayananKategori').innerHTML=(ci||[]).map(x=>`<option value="${x.id}">${esc(x.nama)}</option>`).join('');$('pengeluaranKategori').innerHTML=(co||[]).map(x=>`<option value="${x.id}">${esc(x.nama)}</option>`).join('');$('pelaksana').innerHTML=(st||[]).map(x=>`<option value="${x.id}">${esc(x.nama)}</option>`).join('');['pelayananPayment','penjualanPayment','pengeluaranPayment'].forEach(id=>$(id).innerHTML=(pay||[]).map(x=>`<option value="${x.id}">${esc(x.nama||x.name)}</option>`).join(''));$('produk').innerHTML=prod?.length?prod.map(x=>`<option value="${x.id}" data-price="${x.harga}">${esc(x.nama)} — ${fmt(x.harga)}</option>`).join(''):'<option value="">Belum ada produk aktif</option>';calcSale()}
function calcSale(){const o=$('produk')?.selectedOptions?.[0],q=Number($('produkJumlah')?.value||1);if(o?.dataset.price)$('penjualanNominal').value=Math.round(+o.dataset.price*q)}
async function cashStatus(){try{const s=(await rpc('kasir_status_kas_kasir'))?.[0];if(!s){$('cashBadge').textContent='BELUM DIBUKA';$('cashStatusText').textContent='Kas hari ini belum dibuka.';$('openCashBox').classList.remove('hidden');$('closeCashBox').classList.add('hidden');return}if(s.status==='OPEN'){$('cashBadge').textContent='TERBUKA';$('cashStatusText').textContent='Kas aktif hari ini.';$('openCashBox').classList.add('hidden');$('closeCashBox').classList.remove('hidden')}else{$('cashBadge').textContent='DITUTUP';$('cashStatusText').textContent='Kas hari ini sudah ditutup.';$('openCashBox').classList.add('hidden');$('closeCashBox').classList.add('hidden')}}catch(e){msg('cashMessage',e.message)}}
async function openCash(){const n=+$('openingCash').value;if(!Number.isInteger(n)||n<0){msg('cashMessage','Kas awal tidak boleh negatif.');return}try{await rpc('kasir_buka_kas_harian',{p_kas_awal:n,p_catatan:'Dibuka dari laman Kasir'});$('openingCash').value='';msg('cashMessage','Kas berhasil dibuka.');await cashStatus()}catch(e){msg('cashMessage',e.message)}}
async function closeCash(){const n=+$('closingCash').value,note=$('closingNote').value.trim();if(!Number.isInteger(n)||n<0){msg('cashMessage','Kas fisik tidak boleh negatif.');return}if(!confirm('Tutup kas hari ini?'))return;try{await rpc('kasir_tutup_kas_harian',{p_kas_fisik:n,p_catatan:note||null});$('closingCash').value='';$('closingNote').value='';msg('cashMessage','Kas berhasil ditutup.');await cashStatus()}catch(e){msg('cashMessage',e.message)}}
async function savePelayanan(e){e.preventDefault();msg('pelayananMessage','Menyimpan...');try{await rpc('kasir_input_pelayanan',{p_nama_pasien:$('pasienNama').value.trim(),p_umur:+$('pasienUmur').value,p_kategori_id:+$('pelayananKategori').value,p_pelaksana_id:+$('pelaksana').value,p_metode_pembayaran_id:+$('pelayananPayment').value,p_nominal:+$('pelayananNominal').value,p_catatan:$('pelayananCatatan').value.trim()||null});e.target.reset();msg('pelayananMessage','Tersimpan. Logbook otomatis dibuat.');await masters();await rekap();await patients()}catch(e){msg('pelayananMessage',e.message)}}
async function savePenjualan(e){e.preventDefault();if(!$('produk').value){msg('penjualanMessage','Belum ada produk aktif.');return}msg('penjualanMessage','Menyimpan...');try{await rpc('kasir_input_penjualan',{p_produk_id:$('produk').value,p_jumlah:+$('produkJumlah').value,p_metode_pembayaran_id:+$('penjualanPayment').value,p_nominal:+$('penjualanNominal').value,p_catatan:$('penjualanCatatan').value.trim()||null});e.target.reset();$('produkJumlah').value=1;msg('penjualanMessage','Penjualan tersimpan.');await masters();await rekap()}catch(e){msg('penjualanMessage',e.message)}}
async function savePengeluaran(e){e.preventDefault();msg('pengeluaranMessage','Menyimpan...');try{await rpc('kasir_input_pengeluaran',{p_kategori_id:+$('pengeluaranKategori').value,p_metode_pembayaran_id:+$('pengeluaranPayment').value,p_nominal:+$('pengeluaranNominal').value,p_catatan:$('pengeluaranCatatan').value.trim()});e.target.reset();msg('pengeluaranMessage','Pengeluaran tersimpan.');await rekap()}catch(e){msg('pengeluaranMessage',e.message)}}
async function rekap(){try{const s=(await rpc('kasir_rekap_saya'))?.[0];$('rekapSummary').innerHTML=s?`<div class="stat"><span>Pasien diinput</span><strong>${s.pasien_dilayani}</strong></div><div class="stat"><span>Pelayanan</span><strong>${s.pelayanan}</strong></div><div class="stat"><span>Penjualan</span><strong>${s.penjualan}</strong></div><div class="stat"><span>Pengeluaran</span><strong>${s.pengeluaran}</strong></div>`:'';const r=await rpc('kasir_rekap_saya_detail');$('rekapRows').innerHTML=(r||[]).map(x=>`<tr><td>${esc(x.waktu)}</td><td>${esc(x.jenis)}</td><td>${esc(x.keterangan)}</td><td>${esc(x.pelaksana||'-')}</td></tr>`).join('')}catch(e){msg('pelayananMessage',e.message)}}
async function patients(){try{const r=await rpc('kasir_riwayat_pasien_hari_ini');$('pasienRows').innerHTML=(r||[]).map(x=>`<tr><td>${esc(x.jam)}</td><td>${esc(x.nama_pasien)}</td><td>${x.umur}</td><td>${esc(x.pelayanan)}</td><td>${esc(x.pelaksana)}</td></tr>`).join('')}catch{}}
function showPanel(id){document.querySelectorAll('.panel').forEach(x=>x.classList.add('hidden'));$(id).classList.remove('hidden');document.querySelectorAll('.menu-card').forEach(x=>x.classList.toggle('active',x.dataset.panel===id))}
async function initAdmin(){$('adminLoginForm').onsubmit=adminLogin;$('logoutBtn').onclick=()=>db.auth.signOut({scope:'local'});document.querySelectorAll('.admin-nav-btn').forEach(b=>b.onclick=()=>showAdmin(b.dataset.panel));$('reportBtn').onclick=adminDash;$('txBtn').onclick=adminTx;$('logBtn').onclick=adminLog;$('adminOpenCash').onclick=adminOpen;$('adminCloseCash').onclick=adminClose;const d=today();['reportFrom','reportTo','txFrom','txTo','logFrom','logTo'].forEach(id=>$(id).value=d);const s=(await db.auth.getSession()).data.session;if(s){const role=await rpc('kasir_current_role').catch(()=>null);if(['admin','owner'].includes(String(role).toLowerCase()))enterAdmin();else db.auth.signOut({scope:'local'})}}
async function adminLogin(e){e.preventDefault();msg('loginMessage','Memproses...');const r=await db.auth.signInWithPassword({email:$('adminEmail').value.trim(),password:$('adminPassword').value});if(r.error){msg('loginMessage',r.error.message);return}try{const role=await rpc('kasir_current_role');if(!['admin','owner'].includes(String(role).toLowerCase()))throw new Error('Akun ini bukan Admin.');enterAdmin()}catch(e){msg('loginMessage',e.message);await db.auth.signOut({scope:'local'})}}
function enterAdmin(){$('loginView').classList.add('hidden');$('appView').classList.remove('hidden');adminDash();adminTx();adminLog();adminCash();adminMasters()}
async function adminDash(){try{const d=(await rpc('kasir_admin_dashboard_final',{p_mulai:$('reportFrom').value,p_selesai:$('reportTo').value}))?.[0];$('dashboardStats').innerHTML=d?`<div class="stat"><span>Pelayanan</span><strong>${fmt(d.pelayanan)}</strong></div><div class="stat"><span>Penjualan</span><strong>${fmt(d.penjualan)}</strong></div><div class="stat"><span>Total Pendapatan</span><strong>${fmt(d.total_pendapatan)}</strong></div><div class="stat"><span>Pengeluaran</span><strong>${fmt(d.pengeluaran)}</strong></div><div class="stat"><span>Kas Bersih</span><strong>${fmt(d.kas_bersih)}</strong></div><div class="stat"><span>Transaksi</span><strong>${d.jumlah_transaksi}</strong></div>`:''}catch(e){msg('dashboardMessage',e.message)}}
async function adminTx(){try{const r=await rpc('kasir_admin_transaksi_final',{p_mulai:$('txFrom').value,p_selesai:$('txTo').value,p_subjenis:$('txType').value||null});$('txRows').innerHTML=(r||[]).map(x=>`<tr><td>${new Date(x.tanggal).toLocaleString('id-ID')}</td><td>${esc(x.nomor)}</td><td>${esc(x.subjenis)}</td><td>${esc(x.pasien||x.produk||'-')}</td><td>${esc(x.kategori)}</td><td>${esc(x.pelaksana||'-')}</td><td>${esc(x.operator||'-')}</td><td>${esc(x.metode)}</td><td>${fmt(x.nominal)}</td></tr>`).join('');msg('txMessage',`${r?.length||0} transaksi`)}catch(e){msg('txMessage',e.message)}}
async function adminLog(){try{const r=await rpc('kasir_admin_logbook_final',{p_mulai:$('logFrom').value,p_selesai:$('logTo').value,p_cari:$('logSearch').value.trim()||null});$('logRows').innerHTML=(r||[]).map(x=>{const d=new Date(x.tanggal_waktu);return `<tr><td>${d.toLocaleDateString('id-ID')}</td><td>${d.toLocaleTimeString('id-ID',{hour:'2-digit',minute:'2-digit'})}</td><td>${esc(x.nama_pasien)}</td><td>${x.umur}</td><td>${esc(x.pelayanan)}</td><td>${esc(x.pelaksana)}</td><td>${esc(x.operator)}</td></tr>`}).join('');msg('logMessage',`${r?.length||0} pasien`)}catch(e){msg('logMessage',e.message)}}
async function adminCash(){try{const s=(await rpc('kasir_admin_kas_hari_ini'))?.[0];if(!s){$('adminCashStatus').textContent='BELUM DIBUKA';$('adminCashDetail').textContent='Belum ada kas hari ini.';$('cashStats').innerHTML='';return}$('adminCashStatus').textContent=s.status==='OPEN'?'KAS TERBUKA':'KAS DITUTUP';$('adminCashDetail').textContent=`Kas awal ${fmt(s.kas_awal)} • Sistem ${fmt(s.kas_sistem)}`;$('cashStats').innerHTML=`<div class="stat"><span>Kas Masuk</span><strong>${fmt(s.kas_masuk)}</strong></div><div class="stat"><span>Kas Keluar</span><strong>${fmt(s.kas_keluar)}</strong></div><div class="stat"><span>Kas Sistem</span><strong>${fmt(s.kas_sistem)}</strong></div><div class="stat"><span>Kas Fisik</span><strong>${fmt(s.kas_fisik)}</strong></div><div class="stat"><span>Selisih</span><strong>${fmt(s.selisih)}</strong></div>`;$('adminOpenCash').disabled=true;$('adminOpeningCash').disabled=true;$('adminCloseCash').disabled=s.status!=='OPEN';$('adminClosingCash').disabled=s.status!=='OPEN'}catch(e){msg('adminCashMessage',e.message)}}
async function adminOpen(){try{await rpc('kasir_buka_kas_harian',{p_kas_awal:+$('adminOpeningCash').value,p_catatan:'Dibuka dari Dashboard Admin'});msg('adminCashMessage','Kas berhasil dibuka.');adminCash()}catch(e){msg('adminCashMessage',e.message)}}
async function adminClose(){if(!confirm('Tutup kas hari ini?'))return;try{await rpc('kasir_tutup_kas_harian',{p_kas_fisik:+$('adminClosingCash').value,p_catatan:$('adminClosingNote').value.trim()||null});msg('adminCashMessage','Kas berhasil ditutup.');adminCash()}catch(e){msg('adminCashMessage',e.message)}}
async function adminMasters(){try{const [c,p]=await Promise.all([rpc('kasir_get_kategori',{p_jenis:'PEMASUKAN'}),rpc('kasir_get_produk')]);$('categoryRows').innerHTML=(c||[]).map(x=>`<tr><td>${esc(x.nama)}</td><td>Pemasukan</td><td>Aktif</td></tr>`).join('');$('productRows').innerHTML=(p||[]).map(x=>`<tr><td>${esc(x.nama)}</td><td>${esc(x.kategori)}</td><td>${fmt(x.harga)}</td><td>${x.stok}</td></tr>`).join('')}catch{}}
function showAdmin(id){document.querySelectorAll('.admin-panel').forEach(x=>x.classList.add('hidden'));$(id).classList.remove('hidden');document.querySelectorAll('.admin-nav-btn').forEach(x=>x.classList.toggle('active',x.dataset.panel===id))}
if(isKasir)initKasir();else initAdmin();
