(function(){
const URL='https://kjmotqzbifxsnscvtysz.supabase.co',KEY='sb_publishable_2LKsNXHeEemj9wnxr71eyw_ASH4ZFLK';
const page=document.body.dataset.page,isKasir=page==='kasir';
const client=window.supabase.createClient(URL,KEY,{auth:{storageKey:isKasir?'pmb_yunaji_kasir_session':'pmb_yunaji_admin_session',persistSession:true,autoRefreshToken:true,detectSessionInUrl:false}});
const q=id=>document.getElementById(id),msg=(id,t)=>{if(q(id))q(id).textContent=t||''},fmt=n=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(Number(n)||0),today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Jakarta',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date()),esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\\"':'&quot;',"'":'&#39;'}[c]));
const rpc=async(name,args={})=>{const r=await client.rpc(name,args);if(r.error)throw r.error;return r.data};
function show(id,on){q(id)?.classList.toggle('hidden',!on)}
async function cashStatus(){const s=(await rpc('kasir_status_kas_kasir'))?.[0];if(!s){q('cashBadge').textContent='BELUM DIBUKA';q('cashStatusText').textContent='Kas hari ini belum dibuka.';show('openCashBox',true)}else if(s.status==='OPEN'){q('cashBadge').textContent='TERBUKA';q('cashStatusText').textContent='Kas aktif hari ini.';show('openCashBox',false)}else{q('cashBadge').textContent='DITUTUP';q('cashStatusText').textContent='Kas hari ini sudah ditutup.';show('openCashBox',false)}window.refreshCashGuard?.()}
async function masters(){const [inc,exp,staff,pay,prod]=await Promise.all([rpc('kasir_get_kategori',{p_jenis:'PEMASUKAN'}),rpc('kasir_get_kategori',{p_jenis:'PENGELUARAN'}),rpc('kasir_get_penanggung_jawab'),rpc('kasir_get_metode_pembayaran'),rpc('kasir_get_produk')]);q('pelayananKategori').innerHTML=(inc||[]).map(x=>`<option value="${x.id}">${esc(x.nama)}</option>`).join('');q('pengeluaranKategori').innerHTML=(exp||[]).map(x=>`<option value="${x.id}">${esc(x.nama)}</option>`).join('');q('pelaksana').innerHTML=(staff||[]).map(x=>`<option value="${x.id}">${esc(x.nama)}</option>`).join('');['pelayananPayment','penjualanPayment','pengeluaranPayment'].forEach(id=>q(id).innerHTML=(pay||[]).map(x=>`<option value="${x.id}">${esc(x.nama)}</option>`).join(''));q('produk').innerHTML=(prod||[]).length?(prod||[]).map(x=>`<option value="${x.id}" data-price="${x.harga}" data-stock="${x.stok}">${esc(x.nama)} — ${fmt(x.harga)} | Stok ${x.stok}</option>`).join(''):'<option value="">Belum ada produk aktif</option>';calcSale()}
function calcSale(){const o=q('produk')?.selectedOptions?.[0],n=Number(q('produkJumlah')?.value||1);if(o?.dataset.price)q('penjualanNominal').value=Math.round(Number(o.dataset.price)*n)}
async function rekap(){try{const s=(await rpc('kasir_rekap_saya'))?.[0];if(q('rekapSummary'))q('rekapSummary').innerHTML=s?`<div class="kpi-card accent-pink"><div class="kpi-icon">👥</div><span>Total Pasien</span><strong>${s.pasien_dilayani}</strong></div><div class="kpi-card accent-blue"><div class="kpi-icon">📋</div><span>Total Pelayanan</span><strong>${s.pelayanan}</strong></div><div class="kpi-card accent-green"><div class="kpi-icon">✓</div><span>Selesai</span><strong>${s.pelayanan}</strong></div>`:'';const r=await rpc('kasir_riwayat_transaksi_saya');q('rekapRows').innerHTML=(r||[]).map((x,i)=>`<tr><td>${i+1}</td><td>${esc(x.waktu)}</td><td>${esc(x.nama_pasien||x.produk||x.catatan||'-')}</td><td>${esc(x.kategori||x.subjenis||'-')}</td><td>${esc(x.pelaksana||'-')}</td><td>${esc(x.status)}</td><td>-</td></tr>`).join('')||'<tr><td colspan="7">Belum ada transaksi hari ini.</td></tr>'}catch(e){msg('pelayananMessage',e.message)}}
async function patients(){try{const r=await rpc('kasir_riwayat_pasien_hari_ini');q('pasienRows').innerHTML=(r||[]).map(x=>`<tr><td>${esc(x.jam)}</td><td>${esc(x.nama_pasien)}</td><td>${x.umur}</td><td>${esc(x.pelayanan)}</td><td>${esc(x.pelaksana)}</td></tr>`).join('')||'<tr><td colspan="5">Belum ada pasien hari ini.</td></tr>'}catch(e){msg('pelayananMessage',e.message)}}
async function enterKasir(){const o=(await rpc('kasir_current_operator'))?.[0];if(!o)throw new Error('Operator belum dipilih.');q('welcomeName').textContent=o.staff_name;q('operatorLabel').textContent=o.staff_name;show('loginView',false);show('appView',true);await masters();await cashStatus();await rekap();await patients()}
async function loginKasir(id){try{msg('loginMessage','Membuka sesi kasir...');let s=(await client.auth.getSession()).data.session;if(!s?.user?.is_anonymous){const r=await client.auth.signInAnonymously();if(r.error)throw r.error}await rpc('kasir_set_operator',{p_staff_id:Number(id)});await enterKasir()}catch(e){msg('loginMessage','Login gagal: '+e.message)}}
async function openCash(){const n=Number(q('openingCash').value);if(!Number.isInteger(n)||n<0){msg('cashMessage','Kas awal tidak valid.');return}if(!confirm(`Buka kas hari ini dengan ${fmt(n)}?`))return;try{await rpc('kasir_buka_kas_harian',{p_kas_awal:n,p_catatan:'Dibuka dari laman Kasir'});q('openingCash').value='';msg('cashMessage','Kas berhasil dibuka.');await cashStatus()}catch(e){msg('cashMessage',e.message)}}
async function savePelayanan(e){e.preventDefault();const n=q('pasienNama').value.trim(),u=Number(q('pasienUmur').value),k=Number(q('pelayananKategori').value),p=Number(q('pelaksana').value),m=Number(q('pelayananPayment').value),nom=Number(q('pelayananNominal').value);if(!n||!Number.isInteger(u)||u<0||u>130||!k||!p||!m||nom<=0){msg('pelayananMessage','Lengkapi data pelayanan dengan benar.');return}if(!confirm(`Simpan pelayanan ${n} sebesar ${fmt(nom)}?`))return;try{await rpc('kasir_input_pelayanan',{p_nama_pasien:n,p_umur:u,p_kategori_id:k,p_pelaksana_id:p,p_metode_pembayaran_id:m,p_nominal:nom,p_catatan:q('pelayananCatatan').value.trim()||null});e.target.reset();msg('pelayananMessage','Pelayanan tersimpan. Logbook otomatis dibuat.');await masters();await rekap();await patients()}catch(x){msg('pelayananMessage',x.message)}}
async function savePenjualan(e){e.preventDefault();const id=q('produk').value,n=Number(q('produkJumlah').value),m=Number(q('penjualanPayment').value),nom=Number(q('penjualanNominal').value),stock=Number(q('produk').selectedOptions[0]?.dataset.stock);if(!id){msg('penjualanMessage','Belum ada produk aktif. Tambahkan produk melalui Admin > Data Master.');return}if(n<=0||m<=0||nom<=0){msg('penjualanMessage','Data penjualan tidak valid.');return}if(Number.isFinite(stock)&&n>stock){msg('penjualanMessage',`Stok tidak cukup. Stok tersedia: ${stock}.`);return}if(!confirm(`Simpan penjualan ${q('produk').selectedOptions[0]?.textContent} sebesar ${fmt(nom)}?`))return;try{await rpc('kasir_input_penjualan',{p_produk_id:id,p_jumlah:n,p_metode_pembayaran_id:m,p_nominal:nom,p_catatan:q('penjualanCatatan').value.trim()||null});e.target.reset();q('produkJumlah').value=1;msg('penjualanMessage','Penjualan tersimpan.');await masters();await rekap()}catch(x){msg('penjualanMessage',x.message)}}
async function savePengeluaran(e){e.preventDefault();const k=Number(q('pengeluaranKategori').value),m=Number(q('pengeluaranPayment').value),n=Number(q('pengeluaranNominal').value),c=q('pengeluaranCatatan').value.trim();if(!k||!m||n<=0||!c){msg('pengeluaranMessage','Lengkapi semua data pengeluaran.');return}if(!confirm(`Simpan pengeluaran ${fmt(n)}?`))return;try{await rpc('kasir_input_pengeluaran',{p_kategori_id:k,p_metode_pembayaran_id:m,p_nominal:n,p_catatan:c});e.target.reset();msg('pengeluaranMessage','Pengeluaran tersimpan.');await rekap()}catch(x){msg('pengeluaranMessage',x.message)}}
function showPanel(id){document.querySelectorAll('.panel').forEach(x=>x.classList.add('hidden'));q(id)?.classList.remove('hidden');document.querySelectorAll('.menu-card').forEach(x=>x.classList.toggle('active',x.dataset.panel===id))}
async function adminLogin(e){e.preventDefault();try{const r=await client.auth.signInWithPassword({email:q('adminEmail').value.trim(),password:q('adminPassword').value});if(r.error)throw r.error;const role=await rpc('kasir_current_role');if(!['admin','owner'].includes(String(role).toLowerCase())){await client.auth.signOut({scope:'local'});throw new Error('Akun ini bukan Admin/Owner.')}await enterAdmin()}catch(x){msg('loginMessage',x.message)}}
async function enterAdmin(){show('loginView',false);show('appView',true);const d=today();['reportFrom','reportTo','pelayananFrom','pelayananTo','txFrom','txTo','logFrom','logTo','rpFrom','rpTo'].forEach(id=>{if(q(id))q(id).value=d});await adminDash();await adminCash();await loadAdminMasters()}
function showAdmin(id){document.querySelectorAll('.admin-panel').forEach(x=>x.classList.add('hidden'));q(id)?.classList.remove('hidden');document.querySelectorAll('.admin-nav-btn').forEach(x=>x.classList.toggle('active',x.dataset.panel===id));({dashboardPanel:adminDash,pelayananAdminPanel:adminPelayanan,transaksiPanel:adminTx,pengeluaranAdminPanel:adminPengeluaran,logbookPanel:adminLog,kasPanel:adminCash,rekapPelaksanaPanel:()=>window.initRekapPelaksana?.()})[id]?.()}
async function loadAdminMasters(){try{const [staff,prod]=await Promise.all([rpc('kasir_admin_get_staff'),rpc('kasir_get_produk')]);if(q('productRows'))q('productRows').innerHTML=(prod||[]).map(x=>`<tr><td>${esc(x.nama)}</td><td>${esc(x.kategori)}</td><td>${fmt(x.harga)}</td><td>${x.stok}</td></tr>`).join('')||'<tr><td colspan="4">Belum ada produk aktif.</td></tr>';if(q('pelayananPelaksana'))q('pelayananPelaksana').innerHTML='<option value="">Semua Pelaksana</option>'+(staff||[]).filter(x=>x.aktif).map(x=>`<option>${esc(x.nama)}</option>`).join('');if(q('rekapPelaksanaFilter'))q('rekapPelaksanaFilter').innerHTML='<option value="">Semua Pelaksana</option>'+(staff||[]).filter(x=>x.aktif).map(x=>`<option value="${x.id}">${esc(x.nama)}</option>`).join('')}catch(e){msg('dashboardMessage',e.message)}}
async function adminDash(){try{const d=(await rpc('kasir_admin_dashboard_ui',{p_mulai:q('reportFrom')?.value||today(),p_selesai:q('reportTo')?.value||today()}))?.[0];if(!d)return;q('dashboardStats').innerHTML=`<div class="stat"><span>Total Pasien</span><strong>${d.total_pasien}</strong></div><div class="stat"><span>Total Pelayanan</span><strong>${d.total_pelayanan}</strong></div><div class="stat"><span>Selesai</span><strong>${d.pelayanan_selesai}</strong></div><div class="stat"><span>Pemasukan</span><strong>${fmt(d.total_pemasukan)}</strong></div><div class="stat"><span>Pengeluaran</span><strong>${fmt(d.total_pengeluaran)}</strong></div><div class="stat"><span>Saldo Kas</span><strong>${fmt(d.saldo_kas)}</strong></div>`}catch(e){msg('dashboardMessage',e.message)}}
async function adminPelayanan(){try{const r=await rpc('kasir_admin_transaksi_final',{p_mulai:q('pelayananFrom').value,p_selesai:q('pelayananTo').value,p_subjenis:'PELAYANAN'}),f=q('pelayananPelaksana')?.selectedOptions[0]?.textContent||'';q('pelayananRows').innerHTML=(r||[]).filter(x=>!f||f==='Semua Pelaksana'||x.pelaksana===f).map((x,i)=>`<tr><td>${i+1}</td><td>${new Date(x.tanggal).toLocaleDateString('id-ID')}</td><td>${new Date(x.tanggal).toLocaleTimeString('id-ID',{hour:'2-digit',minute:'2-digit'})}</td><td>${esc(x.pasien||'-')}</td><td>${esc(x.kategori||'-')}</td><td>${esc(x.pelaksana||'-')}</td><td>${esc(x.operator||'-')}</td><td>${esc(x.metode||'-')}</td><td>${fmt(x.nominal)}</td><td>${esc(x.status)}</td></tr>`).join('')||'<tr><td colspan="10">Belum ada data.</td></tr>'}catch(e){msg('dashboardMessage',e.message)}}
async function adminTx(){try{const r=await rpc('kasir_admin_transaksi_final',{p_mulai:q('txFrom').value,p_selesai:q('txTo').value,p_subjenis:q('txType').value||null});q('txRows').innerHTML=(r||[]).map(x=>`<tr><td>${new Date(x.tanggal).toLocaleDateString('id-ID')}</td><td>${esc(x.nomor)}</td><td>${esc(x.subjenis)}</td><td>${esc(x.pasien||x.produk||'-')}</td><td>${esc(x.kategori||'-')}</td><td>${esc(x.pelaksana||'-')}</td><td>${esc(x.operator||'-')}</td><td>${esc(x.metode||'-')}</td><td>${fmt(x.nominal)}</td></tr>`).join('')||'<tr><td colspan="9">Belum ada transaksi.</td></tr>'}catch(e){msg('txMessage',e.message)}}
async function adminLog(){try{const r=await rpc('kasir_admin_logbook_final',{p_mulai:q('logFrom').value,p_selesai:q('logTo').value,p_cari:q('logSearch')?.value?.trim()||null});q('logRows').innerHTML=(r||[]).map(x=>{const d=new Date(x.tanggal_waktu);return `<tr><td>${d.toLocaleDateString('id-ID')}</td><td>${d.toLocaleTimeString('id-ID',{hour:'2-digit',minute:'2-digit'})}</td><td>${esc(x.nama_pasien)}</td><td>${x.umur}</td><td>${esc(x.pelayanan)}</td><td>${esc(x.pelaksana)}</td><td>${esc(x.operator)}</td></tr>`}).join('')||'<tr><td colspan="7">Belum ada logbook.</td></tr>'}catch(e){msg('logMessage',e.message)}}
async function adminPengeluaran(){try{const r=await rpc('kasir_admin_transaksi_final',{p_mulai:q('txFrom')?.value||today(),p_selesai:q('txTo')?.value||today(),p_subjenis:'PENGELUARAN'});q('pengeluaranRows').innerHTML=(r||[]).map(x=>`<tr><td>${new Date(x.tanggal).toLocaleDateString('id-ID')}</td><td>${esc(x.kategori)}</td><td>${esc(x.pasien||'-')}</td><td>${esc(x.operator||'-')}</td><td>${esc(x.metode||'-')}</td><td>${fmt(x.nominal)}</td></tr>`).join('')||'<tr><td colspan="6">Belum ada pengeluaran.</td></tr>'}catch(e){msg('dashboardMessage',e.message)}}
async function adminCash(){try{const r=(await rpc('kasir_admin_kas_hari_ini'))?.[0];if(!r){q('adminCashStatus').textContent='Kas belum dibuka';q('adminCashDetail').textContent='Belum ada kas hari ini.';return}q('adminCashStatus').textContent=r.status==='OPEN'?'Kas TERBUKA':'Kas DITUTUP';q('adminCashDetail').textContent=`Kas awal ${fmt(r.kas_awal)} • Masuk ${fmt(r.kas_masuk)} • Keluar ${fmt(r.kas_keluar)} • Sistem ${fmt(r.kas_sistem)}${r.status==='CLOSED'?` • Fisik ${fmt(r.kas_fisik)} • Selisih ${fmt(r.selisih)}`:''}`;q('adminOpeningCash').disabled=r.status==='OPEN';q('adminCloseCash').disabled=r.status!=='OPEN'}catch(e){msg('adminCashMessage',e.message)}}
async function adminOpen(){const n=Number(q('adminOpeningCash').value);if(!Number.isInteger(n)||n<0){msg('adminCashMessage','Kas awal tidak valid.');return}try{await rpc('kasir_buka_kas_sesi',{p_tanggal:today(),p_kas_awal:n,p_catatan:'Dibuka Admin'});msg('adminCashMessage','Kas berhasil dibuka.');await adminCash()}catch(e){msg('adminCashMessage',e.message)}}
async function adminClose(){const n=Number(q('adminClosingCash').value),note=q('adminClosingNote').value.trim()||null;if(!Number.isFinite(n)||n<0){msg('adminCashMessage','Kas fisik tidak valid.');return}try{await rpc('kasir_tutup_kas_sesi',{p_tanggal:today(),p_kas_fisik:n,p_catatan:note});msg('adminCashMessage','Kas berhasil ditutup.');await adminCash()}catch(e){msg('adminCashMessage',e.message)}}
function boot(){if(isKasir){q('logoutBtn')?.addEventListener('click',async()=>{await client.auth.signOut({scope:'local'});location.href='index.html'});document.querySelectorAll('.menu-card[data-panel]').forEach(b=>b.onclick=()=>showPanel(b.dataset.panel));q('openCashBtn').onclick=openCash;q('pelayananForm').onsubmit=savePelayanan;q('penjualanForm').onsubmit=savePenjualan;q('pengeluaranForm').onsubmit=savePengeluaran;q('produk').onchange=calcSale;q('produkJumlah').oninput=calcSale;client.auth.getSession().then(async({data})=>{if(data.session?.user?.is_anonymous)await enterKasir()})}else{q('adminLoginForm').onsubmit=adminLogin;q('logoutBtn').onclick=async()=>{await client.auth.signOut({scope:'local'});location.href='admin.html'};document.querySelectorAll('.admin-nav-btn').forEach(b=>b.onclick=()=>showAdmin(b.dataset.panel));q('reportBtn').onclick=adminDash;q('txBtn').onclick=adminTx;q('logBtn').onclick=adminLog;q('adminOpenCash').onclick=adminOpen;q('adminCloseCash').onclick=adminClose;q('pelayananBtn')?.addEventListener('click',adminPelayanan);const d=today();['reportFrom','reportTo','pelayananFrom','pelayananTo','txFrom','txTo','logFrom','logTo','rpFrom','rpTo'].forEach(id=>{if(q(id))q(id).value=d});client.auth.getSession().then(async({data})=>{if(data.session&&!data.session.user?.is_anonymous){const role=await rpc('kasir_current_role').catch(()=>null);if(['admin','owner'].includes(String(role).toLowerCase()))await enterAdmin()}})}}
window.rpc=rpc;window.esc=esc;window.fmt=fmt;window.today=today;window.cashStatus=cashStatus;window.enterKasir=enterKasir;window.rekap=rekap;window.patients=patients;window.openCash=openCash;window.showPanel=showPanel;window.adminDash=adminDash;window.adminTx=adminTx;window.adminLog=adminLog;window.adminOpen=adminOpen;window.adminClose=adminClose;window.adminCash=adminCash;window.adminPelayanan=adminPelayanan;window.adminPengeluaran=adminPengeluaran;window.showAdmin=showAdmin;
document.addEventListener('DOMContentLoaded',boot);
})();